---
Este `README.md` principal proporciona una descripción clara del contenido de cada proyecto y la estructura del repositorio, permitiendo a los usuarios navegar y comprender cada carpeta de manera intuitiva.